### ISSUE TITLE
Do you have a manual for install ?

### ISSUE THREAD

**Issue by Jeff-Tall** [PowerShellPlace/GlpiTools#4]
Hi !

I want to try your code but don't know how to use it.

Thanks.

**Comment by PowerShellPlace** [comment]
Hi,
Module isnt finish, so thats why i didnt create manual for it 
Im still working but in my opinion Im on more than a half of work :)

First you have to enable API in GLPI
Second, get the module, copy it into where you store modules, and import it using a command install-module GlpiTools
Third, use command Set-GlpiToolsConfig with values of parameters which i mentioned below

If you want to use it, you have to get
1. AppToken - which you can find in glpi - general/API/fullaccesfromlocalhost/Application token (app_token)
2. UserToken - which you can find in adminstrations/users/{user}/remote access keys/API token
3. PathToGlpi - is a URL - you can find it here - Setup/General/API/URL of the API

**Comment by jfg-fimac** [comment]
Hi !

Thanks for your answer.

I will follow your update. And hope you can do an installation and setup procedure with the prerequisites.

Thank you.

**Comment by PowerShellPlace** [comment]
I added setup procedure

**Comment by Jeff-Tall** [comment]
Thanks you !
