### ISSUE TITLE
Get-GlpiToolsNetworkEquipments with parameter WithNetworkports returns no data

### ISSUE THREAD

**Issue by Geo-Ron** [PowerShellPlace/GlpiTools#5]
Hi,

Testing found the networkequipments parameter WithNetworkPorts returns only the property length.

![image](https://user-images.githubusercontent.com/23144316/59463159-9cf8dc80-8e25-11e9-9614-e67799c29d90.png)

[  4,4 s] Git\restAPI> Get-GlpiToolsNetworkEquipments -NetworkEquipmentId 15 -Parameter WithNetworkports

Length
------
 50277

**Comment by Geo-Ron** [comment]
Looks an issue specific to this network device.
Another one does return info.

**Comment by PowerShellPlace** [comment]
Hi,

Thank you for your comment
Issues like that can occurs when you have MyDashboad plugin
Do you have ? 

Kind Regards
Wojtek

**Comment by PowerShellPlace** [comment]
If issue is resolved and never happened again, I will close the issue
