### ISSUE TITLE
No item ID in search results

### ISSUE THREAD

**Issue by Geo-Ron** [PowerShellPlace/GlpiTools#6]
Hi,

I am trying your module to change data for an asset in GLPI.
But the search based on computername does not return an ID on which I can update the item...

Looked into the code but I am unable to find where it is returned....

**Comment by PowerShellPlace** [comment]
Hi, 
Thank you for comment :) 
I assume that to achieve this you using Get-GlpiToolsComputers -ComputerName
Search in GLPI API works slightly different, to get ID you have to add it to global view inside GLPI website. 
You have to click 
![image](https://user-images.githubusercontent.com/11921969/65144259-3f24f380-da17-11e9-8dea-6f4e96ad8f1f.png)
And Add there ID to the list

This infromation is inside help of this Function, did you read? ;) 
If you need more help, I encourage you to visit Discord - we can go on voice chanel or even I will share my Desktop :)

**Comment by PowerShellPlace** [comment]
@Geo-Ron my response was helpful ?

**Comment by PowerShellPlace** [comment]
If there isnt any response on issue, im closing it
