### ISSUE TITLE
computerId 

### ISSUE THREAD

**Issue by ludovicbernard** [PowerShellPlace/GlpiTools#8]
How to have the computerid with only computername?

**Comment by PowerShellPlace** [comment]
Hi,
Thank you for comment :) 
I assume, you have computer name and you want to get ID of that computer.

This is the situation which I decribed in #6 , I think there is solution :)

**Comment by ludovicbernard** [comment]
ok thanks for the glpi view,
I found a way to do it, here is the method
$ rall = get-glpitoolscomputer -all
$ rcomputer = $ rall | select name, id | where {$ _. name -match "computer"}

$ computer.id

thanks for super glpitools

**Comment by PowerShellPlace** [comment]
Yes, you can do it like that, It's another approach :) maybe not that fast like search function but...

**Comment by ludovicbernard** [comment]
the goal is to find the MAC of the computer.
that she is the command that allows to do that ?

**Comment by PowerShellPlace** [comment]
Look, you can get Computer object with parameter "WithNetworkPorts"
$t = Get-GlpiToolsComputers -ComputerId <id> -Raw -Parameter WithNetworkports
Then
$t._networkports.NetworkPortEthernet

And you will get All informations about network on desired Computer
Here is mac property

**Comment by ludovicbernard** [comment]
yes nickel,
 how to find the arguments "_networkports.NetworkPortEthernet "?

**Comment by ludovicbernard** [comment]
if we have more than one network interface, it takes what interface ?

**Comment by PowerShellPlace** [comment]
Under the variable $t is Computer object, using . (dot) you reffer to parameters :) 
$t | Get-Member gives you better view on available parameters ;)

**Comment by PowerShellPlace** [comment]
It gives you back All interfaces

**Comment by ludovicbernard** [comment]
ok, on the computer, I have
- "Ethernet port", the mac is well in the script
and also
- "Types of imported unknown network ports", does not go back in the script

**Comment by PowerShellPlace** [comment]
Look how I have:
$t = Get-GlpiToolsComputers -ComputerId id -Raw -Parameter WithNetworkports
![image](https://user-images.githubusercontent.com/11921969/65967229-8d97b080-e461-11e9-87ec-08b8817084b8.png)
Then
$t._networkports
![image](https://user-images.githubusercontent.com/11921969/65967305-b15af680-e461-11e9-98de-3f66dc820c36.png)
And
![image](https://user-images.githubusercontent.com/11921969/65967346-c0da3f80-e461-11e9-8355-e66a4cc4410f.png)


And you will see all network interfaces of computer 
After that you have to filter the results for interface you want (Where-Object)

**Comment by ludovicbernard** [comment]
ok , merci.
with the formcreator plugin, does it exist an API?

**Comment by PowerShellPlace** [comment]
Not in mine, maybe later I will implement commands for FormCreator, but this is the future :)

**Comment by ludovicbernard** [comment]
I will follow this module glpitools because it is really very good, nice job. strongly the future.

**Comment by PowerShellPlace** [comment]
Thank you :) I think we can close the issue
